name: Tests

on: [push, workflow_dispatch]

permissions: {}
jobs:
  runPush:
    permissions:
      contents: write # for Update bundles

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Update bundles
      if: ${{ github.repository == 'Recessive/aaMindustryServer' }}
      run: |
        ./gradlew updateBundles

        if [ -n "$(git status --porcelain)" ]; then
          git add core/assets/bundles/*
          git commit -m "Automatic bundle update"
          git push
        fi
    - name: Run unit tests
      run: ./gradlew clean cleanTest test --stacktrace
