name: Tests

on: [push, workflow_dispatch]

permissions: {}
jobs:
  runPush:
    permissions:
      contents: write # for Update bundles

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Update bundles
      if: ${{ github.repository == 'Recessive/aaMindustryServer' }}
      run: |
        ./gradlew updateBundles

        if [ -n "$(git status --porcelain)" ]; then
          git add core/assets/bundles/*
          git commit -m "Automatic bundle update"
          git push
        fi
    - name: Update JITpack repo
      if: ${{ github.repository == 'Recessive/aaMindustryServer' }}
      run: |
        cd ../
        cp -r ./aaMindustryServer ./MindustryJitpack
        cd MindustryJitpack
        git clone --depth 1 https://github.com/Recessive/aaMindustryServerJitpack.git
        rm -rf .git
        cp -r ./MindustryJitpack/.git ./.git
        rm -rf MindustryJitpack
        rm -rf .github
        rm README.md
        git add .
        git commit --allow-empty -m "${GITHUB_SHA}"
        git push https://Anuken:${{ secrets.API_TOKEN_GITHUB }}@github.com/Recessive/aaMindustryServerJitpack
        cd ../aaMindustryServer
    - name: Run unit tests
      run: ./gradlew clean cleanTest test --stacktrace
